variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonarqube

build:
  stage: build
  script:
    - ./gradlew build -x test
    - ./gradlew.bat --stop
test:
  stage: test
  script:
    - ./gradlew test
    - ./gradlew.bat --stop
sonarqube:
  stage: sonarqube
  script:
    - ./gradlew sonarqube
    - ./gradlew.bat --stop
